"""empty message

Revision ID: 378f016b23dd
Revises: 
Create Date: 2022-10-15 14:51:05.349117

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '378f016b23dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'role_users', 'role', ['role_id'], ['id'])
    op.create_foreign_key(None, 'role_users', 'user', ['user_id'], ['id'])
    op.add_column('user', sa.Column('confirmed', sa.Boolean(), nullable=True))
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.drop_column('user', 'confirmed')
    op.drop_constraint(None, 'role_users', type_='foreignkey')
    op.drop_constraint(None, 'role_users', type_='foreignkey')
    # ### end Alembic commands ###
